sonar.projectKey=motionet_compliance-scan-action_83aa6adb-c026-4df9-a1fa-11588fa4eecd
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/build/**,**/coverage/**
